# -*- mode: python; coding: utf-8; -*-

import sys
import os
from os.path import join

import waflib

def options(ctx):
    pass

def configure(ctx):
    # For use when depending on the parser files...
    ctx.env.PARSER_FILES = [
        base + '.py' for base in '__init__', '__main__', 'parser']

def build(ctx):
    for dir, grammar_name in [
            ('hosts_file_parser', 'hosts'), ('vnc_table_generator', 'vncts')]:
        ctx(source=ctx.path.find_resource([dir, grammar_name + '.ebnf']),
            target=ctx.path.find_or_declare([dir, 'parser.py']))

        to_copy = [join(dir, base) for base in ctx.env.PARSER_FILES[:-1]]
        ctx(features='subst', source=to_copy, target=to_copy, is_copy=True)

    # Add the generated Python modules to the module search path.
    sys.path.append(ctx.path.get_bld().abspath())
