# -*- mode: python; coding: utf-8; -*-

import shutil

def _copy_file(tsk):
    shutil.copyfile(tsk.inputs[0].abspath(), tsk.outputs[0].abspath())

def options(ctx):
    pass

def configure(ctx):
    ctx.find_program('python')

def build(ctx):
    ctx(source=ctx.path.find_resource(['vnc_table_generator', 'vncts.ebnf']),
        target=ctx.path.find_or_declare(['vnc_table_generator', 'parser.py']))

    # TODO: Ugly. We appended '.src' to the extension, because we couldn't get
    # the file copy to work with files of the exact same name, using
    # node.get_bld().
    main_node = ctx.path.find_resource([
        'vnc_table_generator', '__main__.py.src'])
    ctx(rule=_copy_file, source=main_node,
        target=main_node.change_ext(ext='.py', ext_in='.py.src'))

    @ctx.rule(target=ctx.path.find_or_declare(
        ['vnc_table_generator', '__init__.py']))
    def _make_init(tsk):
        open(tsk.outputs[0].abspath(), 'w').close()
