#!/usr/bin/env python

"""Generate a table of SSH fingerprints in reStructuredText for the EOS Lab
machines.
"""

import sys
import os
import re
import argparse

import six
from fabric.api import env, execute, run
from fabric.network import disconnect_all
from texttable import Texttable

SSH_KEYGEN_RE = re.compile(
    r'\d+\s+(?P<fingerprint>(?:(?:[0-9a-f]{2}):){15}[0-9a-f]{2})',
    # Don't care about case for hex digits.
    flags=re.IGNORECASE)

# Setup environment.
env.hosts = [
    'eos{0:02}.cis.gvsu.edu'.format(num) for num in xrange(1, 24)
] + [
    'arch{0:02}.cis.gvsu.edu'.format(num) for num in xrange(1, 11)
]
# skip_bad_hosts and parallel are, unfortunately, mutually exclusive. Don't
# see why they have to be, but that's the way it is.
env.skip_bad_hosts = True
# Use the SSH config file to determine username, etc.
env.use_ssh_config = True

def get_fingerprint():
    """Retrieve the SSH fingerprint for a specific machine."""
    output = run(
        'ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key.pub', shell=False)
    # The second element is the fingerprint.
    match = SSH_KEYGEN_RE.match(output)
    if not match:
        # Return (not raise) so that execution can continue when skip_bad_hosts
        # is set. Our choice is between doing that and raising a NetworkError,
        # which is recognized internally by Fabric.
        return ValueError('Unexpected format for remote output of ssh-keygen.')
    return match.group('fingerprint')

def main(argv):
    # Parse args.
    arg_parser = argparse.ArgumentParser(
        prog=argv[0],
        description='Generate a table of SSH fingerprints in reStructuredText'
        ' for machines in the EOS and Arch Labs.')
    arg_parser.add_argument(
        'output_file', type=argparse.FileType('w'),
        help='output .rst file')
    args = arg_parser.parse_args(argv[1:])
    output_file = args.output_file

    # Generate table.
    try:
        results_dict = execute(get_fingerprint)
    finally:
        disconnect_all()

    table = Texttable()
    # The default decoration produces the correct table.
    table.header(['Host', 'Fingerprint'])

    for host, command_output in sorted(six.iteritems(results_dict)):
        # Use the short host name.
        short_hostname = host.split('.')[0]

        fingerprint_text = (
            # Indicate that the host is down in the table.
            'down for maintenance' if
            # Fabric returns the exception if the task failed.
            isinstance(command_output, Exception)
            # Use a fixed-width font for the fingerprint itself.
            else '``{0}``'.format(command_output))
        table.add_row((short_hostname, fingerprint_text))

    with output_file:
        six.print_(table.draw(), file=output_file)

    return 0

if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
